### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by byga12** [pdepviernestm/2023-bienvenida-Elias318#1]
Buenas, tenés un error de ortografía en el segundo párrafo, pusiste "admeas".

Por otro lado, qué artistas de electrónica escuchas?

**Comment by Elias318** [comment]
Holaa , si jajaja no lo vi. Me gustan alguno como Kungs o french montana . Aca te dejo la playlist por si te va jajaja https://open.spotify.com/playlist/1nmLSfstyjHPS6tliyrEPk?si=f9896411dfd54cc5
